# Values must be nested under the dependency name 'nginx'
nginx:
  image:
    repository: "nginx"
    tag: "1.25.1-debian-11-r0"   # <--- APP UPDATE: Change this to deploy new code
  
  replicaCount: 1
  service:
    type: ClusterIP
