nginx:
  image:
    repository: "nginx"
    tag: "1.24.0-debian-11-r0"   # <--- Stable Application Version
  
  replicaCount: 3                # Prod specific config
  service:
    type: LoadBalancer
